# v3 syntax
version: '3'

# Named volumes
volumes:
  # MySQL Data
  pokerfamily-mysql-data:
    driver: local

  # Redis Data
  pokerfamily-redis-data:
    driver: local

services:
  # MySQL (8.0)
  mysql:
    image: mysql:8.0.11
    container_name: pokerfamily-mysql
    volumes:
      # cached flag: The host’s view of the mount is authoritative
      - pokerfamily-mysql-data:/var/lib/mysql:cached
      - ./.docker/mysql/conf.d/pokerfamily.cnf:/etc/mysql/conf.d/pokerfamily.cnf:cached
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=pokerfamily
      - MYSQL_USER=pokerfamily
      - MYSQL_PASSWORD=secret
    networks:
      pokerfamily-backend:

  # Redis
  cache:
    image: redis:4.0
    container_name: pokerfamily-redis
    command: --appendonly yes
    volumes:
      # cached flag: The host’s view of the mount is authoritative
      - pokerfamily-redis-data:/data
    ports:
      - "6380:6379"
    networks:
      pokerfamily-backend:

  # PHP (with Nginx)
  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    container_name: pokerfamily-api
    volumes:
      # delegated flag: The container runtime’s view of the mount is authoritative
      - .:/var/www/app:delegated
    ports:
      - "8082:8080"
    links:
      - mysql
      - cache
      - mail
    networks:
      pokerfamily-frontend:
      pokerfamily-backend:

  # Mailcatcher SMTP Server
  mail:
    image:  ambientum/mailcatcher:latest
    container_name: pokerfamily-mail
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      pokerfamily-backend:

networks:
  pokerfamily-frontend:
    external: true
  pokerfamily-backend:
